# Generated by Django 3.2.3 on 2021-05-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reaction',
        ),
        migrations.AddField(
            model_name='post',
            name='reactions',
            field=models.ManyToManyField(related_name='reactions', through='rareapi.PostReaction', to='rareapi.Reaction'),
        ),
    ]
