# Generated by Django 3.2.3 on 2021-05-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_auto_20210517_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='ended_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
